feat/identity-ui
habralab/garnet-team pull request #126
Opened 2023-10-20 09:50 UTC by Nelfimov

- собраны минимальная тема и компоненты для реализации identity
- добавлен энтрипоинт для identity
- поправлены конфиги `kratos` под наш проект

2023-10-20 10:03 UTC, TorinAsakura requested changes

2023-10-20 10:03 UTC, TorinAsakura commented on ui/icon/icons.interfaces.ts
> +  stroke?: string | boolean | any
эник тут зачем?

2023-10-20 10:03 UTC, TorinAsakura commented on ui/icon/src/AddIcon.tsx
> +        stroke='#353535'
почему не из темы?

2023-10-20 10:03 UTC, TorinAsakura commented on ui/input/src/input.component.tsx
> +export const InputElement = styled.div<any>(
эники

2023-10-20 13:45 UTC, Nelfimov commented on ui/icon/src/AddIcon.tsx
> +        stroke='#353535'
Автогенерация

2023-10-20 13:45 UTC, Nelfimov commented on ui/icon/icons.interfaces.ts
> +  stroke?: string | boolean | any
✅

2023-10-20 13:45 UTC, Nelfimov commented on features/identity/client/fragments/auth-forms/src/recovery-new-password/recovery-new-password-form.component.tsx
> +import { useFlow }           from '@atls/next-identity-integration/dist/src'
✅

2023-10-21 20:37 UTC, TorinAsakura approved these changes

2023-10-21 20:37 UTC, merged