#111 Просмотр количества участников и количества проектов в командах-участниках
habralab/garnet-team pull request #135
Opened 2023-10-22 16:18 UTC by Demorey

2023-10-23 14:00 UTC, picolino requested changes

2023-10-24 15:41 UTC, picolino requested changes

2023-10-24 23:27 UTC, gfg7 requested changes

2023-10-24 23:27 UTC, gfg7 commented on features/project/server/Garnet.Projects.Application/ProjectTeamParticipant/ProjectTeamParticipantEntity.cs
> +    string ProjectId,
У команд тоже есть аватарки, кстати
Тоже нужен консюмер на TeamUpdatedEvent

2023-10-24 23:27 UTC, gfg7 commented on features/project/server/Garnet.Projects.Infrastructure/Api/ProjectsQuery.cs
> +            x.Projects
Лучше не стоит в ProjectTeamParticipantPayload брать ProjectTeamParticipantEntity из application, мне кажется
Вдруг, еще чем обрастет - аудит, например
Лучше сделать отдельную сущность на слое апи

2023-10-24 23:27 UTC, gfg7 commented on features/project/server/Garnet.Projects.Infrastructure/MongoDb/ProjectTeamParticipant/ProjectTeamParticipantRepository.cs
> +        var userParticipantsEntities = userParticipants.Select(ProjectUserDocument.ToDomain).ToArray();
Зачем в application сущность маппить

2023-10-25 08:12 UTC, Demorey commented on features/project/server/Garnet.Projects.Application/ProjectTeamParticipant/ProjectTeamParticipantEntity.cs
> +    string ProjectId,
> Зачем выделять ProjectId в отдельное поле, если искомый проект и так будет в Projects? У тебя запрос участников конкретного проекта, ты и так знаешь, что получишь только его участников, а не всех подряд Для *Document я могу понять - чтобы поиск упростить, но зачем это в application?

Я уже задавал такой вопрос Даниле, так как сетка команд может измениться и нам может вообще не понадобиться список проектов при запросе команд, то пока что решили оставить так

2023-10-25 08:15 UTC, Demorey commented on features/project/server/Garnet.Projects.Application/ProjectTeamParticipant/ProjectTeamParticipantEntity.cs
> +    string ProjectId,
> У команд тоже есть аватарки, кстати Тоже нужен консюмер на TeamUpdatedEvent

Упустил, добавлю

2023-10-25 11:27 UTC, Demorey commented on features/project/server/Garnet.Projects.Infrastructure/Api/ProjectsQuery.cs
> +            x.Projects
> Мне кажется, что в ProjectTeamParticipantPayload стоит просто кол-во проектов передавать, а не прям список В дизайне же у команд в списке проекта просто счетчик общего числа проек

Вроде изначально в задаче так и было указано, предлагаю посмотреть насколько актуально будет возвращать сами сущности, и если что просто отказаться и перейти на счетчик

2023-10-25 11:28 UTC, Demorey commented on features/project/server/Garnet.Projects.Infrastructure/Api/ProjectsQuery.cs
> +            x.Projects
> Лучше не стоит в ProjectTeamParticipantPayload брать ProjectTeamParticipantEntity из application, мне кажется Вдруг, еще чем обрастет - аудит, например Лучше сделать отдельную сущность на слое апи

Пока оставлю так, если будет что-то прикручивать, то в рамках задачи пересоздам сущность

2023-10-25 14:03 UTC, picolino commented on features/project/server/Garnet.Projects.Application/ProjectTeamParticipant/ProjectTeamParticipantEntity.cs
> +    string ProjectId,
> Зачем выделять ProjectId в отдельное поле, если искомый проект и так будет в Projects? У тебя запрос участников конкретного проекта, ты и так знаешь, что получишь только его участников, а не всех подряд Для *Document я могу понять - чтобы поиск упростить, но зачем это в application?

Все верно, это "на будущее". Чем больше данных у тебя есть в слое приложения тем проще ими манипулировать при дальнейшей эволюции приложения.

2023-10-25 14:27 UTC, picolino requested changes

2023-10-25 14:27 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Support/ProjectTeamParticipantDocumentBuilder.cs
> +        new ProjectDocument()
Плохо
У тебя получается что в создаваемом документе есть ссылки на несуществующих пользователя и проект.
Здесь нужно просто проинициализировать пустой список `new List<***>();`. Этого достаточно

2023-10-25 14:27 UTC, picolino commented on features/project/server/Garnet.Projects.Infrastructure/MongoDb/ProjectTeam/ProjectTeamDocument.cs
> +        public string[] UserParticipantId { get; set; } = null!;
`UserParticipantIds`

2023-10-26 04:48 UTC, picolino approved these changes

2023-10-26 04:48 UTC, merged