feat/user-ui
habralab/garnet-team pull request #141
Opened 2023-10-24 12:57 UTC by Amiditin

Resolves #137

#### Запуск
`yarn workspace @user/renderer-entrypoint dev`

#### Cсылки:
- Мой профиль [localhost](http://localhost:3000/user/6516e88d723450ac19495148)
- Мои команды [localhost](http://localhost:3000/user/teams/6516e88d723450ac19495148)
- Профиль пользователя [localhost](http://localhost:3000/user/6516e88d723450ac19495abc)
- Команды пользователя [localhost](http://localhost:3000/user/teams/6516e88d723450ac19495abc)

2023-10-24 13:21 UTC, Nelfimov requested changes
Перенеси энтрипоинт в `common/client`

2023-10-24 13:21 UTC, Nelfimov commented on features/user/client/entrypoints/renderer/.gitignore
> +.next
Не нужен, в рутовом есть

2023-10-24 13:21 UTC, Nelfimov commented on features/user/client/entrypoints/renderer/src/.gitignore
> +.next
Не нужен, в рутовом есть

2023-10-24 13:21 UTC, Nelfimov commented on features/user/client/entrypoints/renderer/package.json
> +  "peerDependencies": {
Не нужно

2023-10-24 13:21 UTC, Nelfimov commented on features/user/client/fragments/header-fragment/src/header.component.tsx
> +                <TabItem active={url === currentPathname}>
либо так либо `window.location.href.includes(...)`

2023-10-24 13:21 UTC, Nelfimov commented on ui/avatar/src/avatar.component.tsx
> +          borderRadius: shape === 'circle' ? '100%' : theme.radii.medium,
100% тоже в теме как `full`

2023-10-24 13:21 UTC, Nelfimov commented on ui/form/src/form-user/form-user.interfaces.ts
> +  avatar: any
конкретизировать сможешь?

2023-10-24 13:21 UTC, Nelfimov commented on ui/form/src/form-team/form-team.interfaces.ts
> +  avatar: any
Конкретизировать

2023-10-24 13:21 UTC, Nelfimov commented on ui/form/src/form-project/form-project.interfaces.ts
> +  avatar: any
Конкретизировать

2023-10-24 13:21 UTC, Nelfimov commented on ui/input/src/multiselect/data/mock.ts
> +  'SMM',
Сделай через `react-intl` - тут можешь хранить ID

2023-10-24 13:21 UTC, Nelfimov commented on .gitignore
> +.yarn/sdks
уф

2023-10-24 14:54 UTC, Amiditin commented on features/user/client/fragments/header-fragment/src/header.component.tsx
> +                <TabItem active={url === currentPathname}>
У `includes` по идее будет проблема c url вида `/user/teams` и `/team/:id`

2023-10-24 14:56 UTC, Amiditin commented on ui/form/src/form-user/form-user.interfaces.ts
> +  avatar: any
Думал про тип _файла_ для этого поля, но по идее при загрузке img можно превью создать, так что поставил `string`

2023-10-24 14:57 UTC, Nelfimov commented on features/user/client/fragments/header-fragment/src/header.component.tsx
> +                <TabItem active={url === currentPathname}>
Тогда согласен, оставляем твой подход.

2023-10-24 15:33 UTC, Nelfimov submitted a review, later dismissed
перенеси фрагменты и страницы так же к `common/client` и запрашивай ревью дальше

2023-10-25 07:39 UTC, Nelfimov approved these changes

2023-10-25 23:13 UTC, TorinAsakura requested changes

2023-10-25 23:13 UTC, TorinAsakura commented on ui/modal/src/backdrop/backdrop.styles.ts
> +  backgroundColor: 'rgba(53, 53, 53, 0.5)',
вынеси в тему

2023-10-25 23:13 UTC, TorinAsakura commented on utils/helpers/src/get-depend-of-number-word.ts
> + * getDependOfNumberWord(5, ['День', 'Дня', 'Дней'])) // return 'Дней'
зачем? этот функционал есть в intl

2023-10-26 18:20 UTC, merged