#89 Владелец команды может удалить команду из состава проекта
habralab/garnet-team pull request #148
Opened 2023-10-24 18:46 UTC by gfg7

2023-10-24 21:56 UTC, picolino requested changes

2023-10-24 21:56 UTC, picolino commented on common/server/Garnet.Common.Infrastructure/Support/ResultErrorHandler.cs
> +                throw new QueryException(errors);
Го от дублирования тут попробуем избавиться, меняться не будет скорее всего логика

2023-10-24 21:56 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamLeaveProject/TeamLeaveProjectNotice.cs
> +    public record TeamLeaveProjectNotice(
Это что за класс такой - Notice?

2023-10-24 23:30 UTC, gfg7 commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamLeaveProject/TeamLeaveProjectNotice.cs
> +    public record TeamLeaveProjectNotice(
Не было идей для нормального названия
Это явно не request, команда выходит из состава проекта - ничье разрешение не нужно, поэтому уведомление

2023-10-25 11:26 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamLeaveProject/TeamLeaveProjectNotice.cs
> +    public record TeamLeaveProjectNotice(
Лучше давай жестко разделим на Input и Payload как и везде
Единообразие - ключ к простому коду, будем добавлять новых типов сущностей - скатимся в болото
Если это концептуально один и тот же объект - можно отнаследовать Payload от Input'а, но классы должны быть разными

2023-10-26 05:10 UTC, picolino approved these changes

2023-10-26 05:10 UTC, merged