feat/project-ui
habralab/garnet-team pull request #150
Opened 2023-10-25 14:33 UTC by Amiditin

Resolves #144 

#### Запуск
`yarn workspace @app/renderer-entrypoint dev`

#### Cсылки:
- Мой проект [localhost](http://localhost:3001/project/0)
- Страница проекта [localhost](http://localhost:3001/project/1)
- Поиск проекта [localhost](http://localhost:3001/project)

2023-10-26 06:59 UTC, Nelfimov requested changes

2023-10-26 06:59 UTC, Nelfimov commented on ui/card/src/card.component.tsx
> +export const Card: FC<CardProps> = ({ url, ...props }) => {
Вынеси в отдельный файл

2023-10-27 06:25 UTC, Nelfimov requested changes
Обрати внимание на баг

<details>

https://github.com/habralab/garnet-team/assets/44067768/61362d58-b478-494a-8f17-6a0ef6866058

</details>

2023-10-27 06:25 UTC, Nelfimov commented on shared/fragments/modals/src/modal-create-project/modal-create-project.component.tsx
> +const defaultFormValues: FormProjectValues = { name: '', description: '', tags: [], avatar: '' }
в отдельный файл рядом

2023-10-27 06:25 UTC, Nelfimov commented on shared/fragments/modals/src/modal-create-team/modal-create-team.component.tsx
> +const defaultFormValues: FormTeamValues = { name: '', description: '', tags: [], avatar: '' }
В отдельный файл

2023-10-27 06:25 UTC, Nelfimov commented on shared/fragments/modals/src/modal-edit-team/helpers/get-form-values.helper.ts
> +export const getFormValues = (team?: Team): FormTeamValues => ({
дубликат у modal-edit-project. Может унифицировать?

2023-10-27 06:25 UTC, Nelfimov commented on ui/input/src/search/search.component.tsx
> +const Container = styled.div(({ type }: { type?: HTMLInputTypeAttribute }) => ({
Тут можно тогда воспользоваться `Column` вместо `div`

2023-10-27 13:50 UTC, Amiditin commented on shared/fragments/modals/src/modal-edit-team/helpers/get-form-values.helper.ts
> +export const getFormValues = (team?: Team): FormTeamValues => ({
Вынес в ../helpers

2023-10-27 13:53 UTC, Amiditin commented
> Обрати внимание на баг

В следующем PR переписал логику с useSelect на useLayer, и такого рода проблемы пофиксились

2023-10-27 14:12 UTC, Nelfimov approved these changes

2023-10-27 23:06 UTC, TorinAsakura requested changes
@Nelfimov возвращаю тебе на ревью

2023-10-27 23:06 UTC, TorinAsakura commented on common/client/fragments/profile-fragment/src/button-edit-profile/button-edit-profile.component.tsx
> +  const closeModal = () => setModalOpen(false)
можно же сделать toggle

2023-10-27 23:06 UTC, TorinAsakura commented on common/client/fragments/profile-fragment/src/profile-projects/profile-projects.component.tsx
> +        style={{ gap: 32, gridTemplateColumns: `repeat(auto-fill, 284px)` }}
предполагаю, это должно быть где-то в теме или хотя бы в константах?

2023-10-27 23:06 UTC, TorinAsakura commented on common/client/fragments/project-profile-fragment/src/profile-description/profile-description.component.tsx
> +      <Row flexWrap='wrap' maxHeight={72} overflow='hidden' style={{ gap: 10 }}>
старайся не использовать style в принципе

2023-10-30 06:52 UTC, Nelfimov requested changes
Доработать замечания

2023-10-30 14:21 UTC, TorinAsakura commented
> Доработать замечания

конфликты?

2023-10-30 20:44 UTC, Amiditin commented
@Nelfimov 
Это же твои [ошибки](https://github.com/habralab/garnet-team/pull/150/checks?check_run_id=18200412977)? 
Когда они исправятся `Release` не будет падать? 
Или же временно поставить `ignoreBuildErrors: true` ?

2023-10-30 20:52 UTC, Nelfimov commented
> @Nelfimov Это же твои [ошибки](https://github.com/habralab/garnet-team/pull/150/checks?check_run_id=18200412977)? Когда они исправятся `Release` не будет падать? Или же временно поставить `ignoreBuildErrors: true` ?

Генератор сюда по ошибке попал. Можешь сносить под чистую.

2023-10-31 06:29 UTC, Nelfimov requested changes
Ошибки чеков

2023-10-31 18:48 UTC, Nelfimov requested changes
Давай отключать ignoreBuildErrors и идти правильным путем. Ошибки можешь смотреть в tsbuildinfo в .next

2023-11-01 09:32 UTC, Nelfimov approved these changes

2023-11-01 22:55 UTC, TorinAsakura submitted a review, later dismissed

2023-11-01 22:56 UTC, merged