#140 Пользователь может создать задачу внутри проекта
habralab/garnet-team pull request #154
Opened 2023-10-26 12:34 UTC by Demorey

2023-10-27 05:02 UTC, picolino requested changes

2023-10-27 05:02 UTC, picolino commented on features/project/server/Garnet.Projects.Infrastructure/MongoDb/ProjectTask/ProjectTaskDocument.cs
> +    public string[] Tags { get; set; } = null!;
На полях должны стоять `{ get; init; }`, что бы не было соблазна поменять часть документа.

2023-10-27 05:07 UTC, picolino reviewed
Еще важный момент.
У нас будет поддержка ссылок на другие задачи в description'е.

Это значит, что нам необходимо вводить дополнительный числовой идентификатор задачи, чтобы было проще вводить их в description. Поскольку задача создается в рамках проекта - в каждом проекте каждая новая задача должна идти с идентификатором 1, 2, 3 и так далее.

2023-10-27 08:39 UTC, Demorey commented on features/project/server/Garnet.Projects.Application/ProjectTask/ProjectTaskEntity.cs
> +    string? UserExecutorId,
Скорее всего нам нужно будет на странице просмотра задачи сразу отображать у исполнителя и имя и аватар, делать массив ProjectUserEntity выглядит более целесообразно

2023-10-27 08:59 UTC, Demorey commented
> Еще важный момент. У нас будет поддержка ссылок на другие задачи в description'е.
> 
> Это значит, что нам необходимо вводить дополнительный числовой идентификатор задачи, чтобы было проще вводить их в description. Поскольку задача создается в рамках проекта - в каждом проекте каждая новая задача должна идти с идентификатором 1, 2, 3 и так далее.

Тогда добавлю в ProjectEntity поле TasksCounter, и буду в нем инкременить счетчик с каждой новой задачей. (при удалении задачи счетчик не уменьшается)

2023-10-28 16:59 UTC, picolino requested changes

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectDelete/ProjectDeleteSteps.cs
> +        project = project with { AuditInfo = audit };
Сделай просто внутри ProjectDocumentBuilder'а генерацию дефолтной аудитной информации и сделай ее переопределение как метод билдера:

WithAuditInfo(...)

Или можно даже еще глубже сделать:

WithCreatedBy(...)

который внутри будет в аудитной информации проставлять нужного пользака. Так меньше кода получится. Сделай так во всех местах где ты добавлял ручное создание аудитной информации

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectEditDescription/ProjectEditDescriptionSteps.cs
> +        project = project with { AuditInfo = audit };
Тут

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectFilter/ProjectFilterSteps.cs
> +        project = project with { AuditInfo = audit };
Тут

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectFilter/ProjectFilterSteps.cs
> +        project = project with { AuditInfo = audit };
Тут

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectGet/ProjectGetSteps.cs
> +        project = project with { AuditInfo = audit };
Тут

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectTeamParticipantsUsersAndProjectsGet/ProjectTeamParticipantsUsersAndProjectsGetSteps.cs
> +            project = project with { AuditInfo = audit };
Тут

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Support/ProjectTaskDocumentBuilder.cs
> +    public ProjectTaskDocumentBuilder WithUserExecutorId(string[] userExecutorIds)
WithUserExecutorIds тогда

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.Application/ProjectTask/ProjectTaskEntity.cs
>      string? TeamExecutorId,
Команд исполнителей тоже может быть множество, исходя из ТЗ

2023-10-28 16:59 UTC, picolino commented on features/project/server/Garnet.Projects.Infrastructure/Api/ProjectTask/ProjectTaskCreatePayload.cs
> +    string[] Labels
А вод в пейлоад нужно отдать созданный числовой идентификатор задачи

2023-10-28 20:32 UTC, picolino requested changes

2023-10-28 20:32 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectDelete/ProjectDeleteSteps.cs
> +        project = project with { AuditInfo = audit };
А тут забыл?)

2023-10-28 20:32 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Support/ProjectDocumentBuilder.cs
> +        _auditInfo = new AuditInfoDocument(DateTime.UtcNow, username, DateTime.UtcNow, username, 0);
Тут лучше не создавать целый объект полностью, а создать новый на основании текущего:

_auditInfo = _auditInfo with { CreatedBy = username }

2023-10-28 20:32 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Support/ProjectTaskDocumentBuilder.cs
> +        _auditInfo = new AuditInfoDocument(DateTime.UtcNow, username, DateTime.UtcNow, username, 0);
Same

2023-10-28 20:45 UTC, picolino approved these changes

2023-10-28 20:45 UTC, merged