#175 Участникам команды приходит уведомление о решении по заявке на вступление в проект
habralab/garnet-team pull request #185
Opened 2023-10-29 20:19 UTC by gfg7

Пока уведомление по решению приходит только владельцу команды

2023-10-30 18:40 UTC, picolino requested changes

2023-10-30 18:40 UTC, picolino commented on features/project/server/Garnet.Projects.Application/ProjectTeamJoinRequest/Notifications/ProjectTeamJoinRequestEntityNotificationsExtensions.cs
> +        public static SendNotificationCommandMessage CreateProjectTeamJoinRequestDecideNotification(this ProjectTeamJoinRequestEntity projectTeamJoinRequest, ProjectEntity project, string teamOwnerUs
Create в названии метода некорректный глагол в этом случае.

2023-10-31 17:56 UTC, gfg7 commented on features/project/server/Garnet.Projects.Application/ProjectTeamJoinRequest/Notifications/ProjectTeamJoinRequestEntityNotificationsExtensions.cs
> +        public static SendNotificationCommandMessage CreateProjectTeamJoinRequestDecideNotification(this ProjectTeamJoinRequestEntity projectTeamJoinRequest, ProjectEntity project, string teamOwnerUs
Предполагалось ```Создать [ивент] Уведомление ```, как в остальных из мастера
Какие могут быть другие варианты и почему тут не подходит?

2023-10-31 18:23 UTC, picolino commented on features/project/server/Garnet.Projects.Application/ProjectTeamJoinRequest/Notifications/ProjectTeamJoinRequestEntityNotificationsExtensions.cs
> +        public static SendNotificationCommandMessage CreateProjectTeamJoinRequestDecideNotification(this ProjectTeamJoinRequestEntity projectTeamJoinRequest, ProjectEntity project, string teamOwnerUs
Сорян, глаз замылился, апрув

2023-10-31 18:23 UTC, picolino approved these changes

2023-10-31 18:24 UTC, merged