feat/team-ui
habralab/garnet-team pull request #194
Opened 2023-10-30 13:35 UTC by Amiditin

Resolves #151 

#### Запуск
`yarn workspace @app/renderer-entrypoint dev`

#### Cсылки:
- Моя команда [localhost](http://localhost:3001/team/0)
- Страница команды [localhost](http://localhost:3001/team/1)
- Поиск команды [localhost](http://localhost:3001/team)
- Поиск специалиста [localhost](http://localhost:3001/team/invite)

2023-10-31 06:28 UTC, Nelfimov requested changes

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-fragment/src/team.component.tsx
> +            <Row flexWrap='wrap' style={{ gap: 10 }}>
Без `style` и `gap` сможешь?

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-fragment/src/team.component.tsx
> +                  style={{ gap: 22, gridTemplateColumns: 'repeat(auto-fill, 150px)' }}
Аналогично - без `style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-invite-fragment/src/team-invite.component.tsx
> +            <Row flexWrap='wrap' style={{ gap: 10 }}>
`style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-invite-fragment/src/team-invite.component.tsx
> +                  style={{ gap: 22, gridTemplateColumns: 'repeat(auto-fill, 150px)' }}
`style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-profile-fragment/src/profile-description/profile-description.component.tsx
> +  <Row fill flexWrap='wrap' style={{ gap: 32 }} justifyContent='space-between'>
`style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-profile-fragment/src/profile-description/profile-description.component.tsx
> +      <Row flexWrap='wrap' maxHeight={72} overflow='hidden' style={{ gap: 10 }}>
`style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-profile-fragment/src/profile-participants/profile-participants.component.tsx
> +          style={{ gap: 17, gridTemplateColumns: `repeat(auto-fill, 74px)` }}
`style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-profile-fragment/src/profile-projects/button-create-project/button-create-project.component.tsx
> +      <Button variant='secondary' size='small' onClick={openModal} style={{ paddingLeft: 20 }}>
`style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/team-profile-fragment/src/profile-projects/profile-projects.component.tsx
> +        style={{ gap: 22, gridTemplateColumns: `repeat(auto-fill, 180px)` }}
`style`

2023-10-31 06:28 UTC, Nelfimov commented on common/client/fragments/user-teams-fragment/src/list-teams/list-teams.component.tsx
> +          style={{ justifyContent: 'center' }}
`style` здесь и ниже

2023-10-31 06:28 UTC, Nelfimov commented on shared/fragments/modals/src/modal-participants/list-participants/list-participants.component.tsx
> +            <Column width='100%' height='auto' justifyContent='center'>
`fill`?

2023-10-31 06:28 UTC, Nelfimov commented on shared/fragments/modals/src/modal-participants/list-participants/list-participants.component.tsx
> +                <Column width='100%' height='auto' justifyContent='center'>
`fill`

2023-10-31 06:28 UTC, Nelfimov commented on shared/fragments/modals/src/modal-participants/user-request-block/user-request-block.component.tsx
> +const getDaysAgo = (date: string): number =>
В отдельный файл

2023-10-31 06:28 UTC, Nelfimov commented on shared/fragments/modals/src/modal-participants/user-request-block/user-request-block.component.tsx
> +      <Column width='100%' height='auto' justifyContent='center'>
`fill`

2023-10-31 06:28 UTC, Nelfimov commented on shared/fragments/modals/src/modal-participants/user-request-block/user-request-block.component.tsx
> +          <Row flexWrap='wrap' maxHeight={22} overflow='hidden' style={{ gap: 10 }}>
`style`

2023-10-31 06:28 UTC, Nelfimov commented on shared/fragments/modals/src/modal-participants/modal-participants.component.tsx
> +      onOk={handleSubmit}
Нейминг - лучше какой нибудь `onConfirm`

2023-10-31 06:28 UTC, Nelfimov commented on shared/fragments/modals/src/modal-participants/modal-participants.component.tsx
> +      okText={formatMessage({ id: isMyTeam ? 'shared_ui.save' : 'shared_ui.modal.close' })}
`confirmationText` или аналог

2023-10-31 11:49 UTC, Amiditin commented on common/client/fragments/team-fragment/src/team.component.tsx
> +            <Row flexWrap='wrap' style={{ gap: 10 }}>
Чем gap плох?

2023-10-31 11:50 UTC, Amiditin commented on shared/fragments/modals/src/modal-participants/list-participants/list-participants.component.tsx
> +            <Column width='100%' height='auto' justifyContent='center'>
Без `height='auto'` почему-то `justifyContent='center'` не работает :/

2023-10-31 15:20 UTC, Nelfimov commented on common/client/fragments/team-fragment/src/team.component.tsx
> +            <Row flexWrap='wrap' style={{ gap: 10 }}>
`gap` не плох, однако ты пишешь его через `style` - надо же все таки следовать по максимуму стандартным пропсам.

2023-11-01 06:14 UTC, Nelfimov approved these changes

2023-11-01 22:42 UTC, TorinAsakura approved these changes
Поправь замечания в следующих ПРах пожалуйста

2023-11-01 22:42 UTC, TorinAsakura commented on common/client/fragments/project-profile-fragment/src/profile-teams/profile-teams.component.tsx
> +          opacity={0.6}
вынести в тему, встречается уже не впервые

2023-11-01 22:42 UTC, TorinAsakura commented on shared/fragments/modals/src/modal-participants/user-request-block/user-request-block.component.tsx
> +        url={`/user/${id}`}
урлы надо по-хорошему выносить в константы, наружу

2023-11-01 22:42 UTC, TorinAsakura commented on ui/button/src/styles/shape/button.shape-styles.ts
> +  paddingRight: 0.01,
это как вообще?

2023-11-01 22:42 UTC, merged

2023-11-02 10:09 UTC, Amiditin commented on ui/button/src/styles/shape/button.shape-styles.ts
> +  paddingRight: 0.01,
Нужны были 0 падинги, но вместо них подставляется size. По идее в hyperion нужно вместо ` || ` поставить ` ?? ` .

https://github.com/atls/hyperion/blob/b20a60c089d6c56f4f6b6e1df3a0700fadedafb9/ui-parts/button/src/shape/shape.styles.ts#L69-L70

2023-11-02 11:39 UTC, Amiditin commented on ui/button/src/styles/shape/button.shape-styles.ts
> +  paddingRight: 0.01,
https://github.com/atls/hyperion/pull/517