feat/client-graphql
habralab/garnet-team pull request #221
Opened 2023-11-03 14:45 UTC by Amiditin

Resolves #207

2023-11-04 08:53 UTC, Nelfimov requested changes
Необходимо по максимуму логику, `useEffect` вынести из фрагментов и держать в хуках.

2023-11-04 08:53 UTC, Nelfimov commented on shared/data/src/helpers/get-client.helper.ts
> +    // uri: 'https://stage.garnet.pet-project.habr.com/api/sandbox',
Комменты в мастер не должны попадать. Либо `TODO`

2023-11-04 08:53 UTC, Nelfimov commented on shared/fragments/forms/src/button-upload-photo/button-upload-photo.component.tsx
> +  const [file, setFile] = useState<File>()
Функционал загрузки в кастомный хук

2023-11-04 08:53 UTC, Nelfimov commented on shared/fragments/modals/src/modal-edit-project/modal-edit-project.component.tsx
> +  const [submitDisabled, setSubmitDisabled] = useState<boolean>(true)
Компонент перегружен, вытащи в хук по максимуму

2023-11-04 08:53 UTC, Nelfimov commented on shared/fragments/modals/src/modal-edit-team/modal-edit-team.component.tsx
> +  const [submitDisabled, setSubmitDisabled] = useState<boolean>(true)
Перегружен, в хук

2023-11-04 08:53 UTC, Nelfimov commented on shared/fragments/modals/src/modal-edit-user/modal-edit-user.component.tsx
> +  const [submitDisabled, setSubmitDisabled] = useState<boolean>(true)
Перегружен, в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/header-fragment/src/header.component.tsx
> +                  <TabItem active={`/${url.split('/')[1]}` === currentPathname}>
Вынеси условие в тело, а еще лучше в хэлперы

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/header-fragment/src/header.constants.ts
>  export const navigationItems = [
Добавь интерфейс, можно хоть с `enum`

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/onboarding-fragment/src/enter-description/enter-description.component.tsx
> +  const handleSubmit = async () => {
Попробуй в кастомный хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/onboarding-fragment/src/enter-skills/enter-skills.component.tsx
> +  const handleSubmit = async () => {
В хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/onboarding-fragment/src/upload-photo/upload-photo.component.tsx
> +  const handleSubmit = async () => {
В хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/onboarding-fragment/src/onboarding.component.tsx
> +  useEffect(() => {
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/profile-fragment/src/profile-avatar/profile-avatar.component.tsx
> +    <Avatar size={284} image={user?.avatarUrl} color='gray'>
Может ли быть случай когда у пользователя нет аватарки?

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/profile-fragment/src/profile.component.tsx
> +    if (fetchedUser) {
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/project-fragment/src/project.component.tsx
> +  /** @todo search params to url query */
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/project-profile-fragment/src/project-profile.component.tsx
> +    if (fetchedProject) {
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/team-fragment/src/team.component.tsx
> +  /** @todo search params to url query */
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/team-invite-fragment/src/team-invite.component.tsx
> +  const { users } = useGetUsers({ search: '', skip: 0, tags: [], take: 0 })
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/team-profile-fragment/src/profile-actions/button-join-request/button-join-request.component.tsx
> +  const handleRequest = async () => {
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/team-profile-fragment/src/team-profile.component.tsx
> +    if (fetchedTeam) {
Логику в хук

2023-11-04 08:53 UTC, Nelfimov commented on common/client/fragments/user-teams-fragment/src/user-teams.component.tsx
> +  const { user, teams } = useGetUser({ id: queryId, skip: 0, take: 20 })
Логику в хук

2023-11-06 18:14 UTC, Amiditin commented on common/client/fragments/profile-fragment/src/profile-avatar/profile-avatar.component.tsx
> +    <Avatar size={284} image={user?.avatarUrl} color='gray'>
Только при первом входе, когда он не проходит onboarding. Сейчас сделано так что если у пользователя нет аватарки/описания/скилов его редиректит из профиля на onboarding.

2023-11-07 06:10 UTC, Nelfimov approved these changes
Делай правку и дальше запрашивай

2023-11-07 06:10 UTC, Nelfimov commented on shared/data/src/helpers/get-client.helper.ts
> +      uri: process.env.NEXT_BACKEND_URL,
Эта переменная должна быть доступна для браузера, соответственно надо соблюдать конвенцию по наименованию: https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

2023-11-07 06:10 UTC, Nelfimov commented on shared/data/src/helpers/get-client.helper.ts
> +      uri: process.env.NEXT_BACKEND_URL,
Ну и фоллбэк нужен в духе `... ?? ...`

2023-11-07 12:14 UTC, Nelfimov approved these changes

2023-11-07 13:04 UTC, TorinAsakura approved these changes
- затычки в виде хелперов нужно выносить на сторону бэкенда
- местами не используется fill, когда он нужен
- местами всё ещё видна мешанина из логики и интерфейсной части
- кое-где опущены контексто-зависимые имплементы

2023-11-07 13:04 UTC, merged