Feat/projects
habralab/garnet-team pull request #30
Opened 2023-09-28 19:40 UTC by Demorey

2023-09-28 23:11 UTC, TorinAsakura commented
Полагаю, парни, вам бы стоило тоже сделать чеки

2023-09-29 02:11 UTC, picolino commented
> Полагаю, парни, вам бы стоило тоже сделать чеки

На этой недельке забацаю как раз

2023-09-29 08:14 UTC, picolino requested changes

2023-09-29 08:14 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectCreate/ProjectCreateSteps.cs
> +    public async Task GivenСуществуетПользователь(string username)
При сборке проекта увидишь тут warning, поправь

2023-09-29 08:14 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectCreate/ProjectCreateSteps.cs
> +        var user = GiveMe.User().WithId(id);
Строчка лишняя

2023-09-29 08:14 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Support/ProjectDocumentBuilder.cs
> +    public ProjectDocumentBuilder WithUserName(string userId)
WithOwnerUserId наверное =)

2023-09-29 08:54 UTC, picolino approved these changes

2023-09-29 08:54 UTC, merged