#11 Пользователь может удалить свою команду
habralab/garnet-team pull request #40
Opened 2023-09-30 20:16 UTC by gfg7

2023-09-30 20:23 UTC, picolino requested changes

2023-09-30 20:23 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamsMutation.cs
> +                throw new QueryException(result.Errors[0].Message);
Тут лучше выкинуть AggregateException из нескольких ошибок (всех которые находятся в резалте). HotChocolate умеет с ними работать

2023-09-30 20:50 UTC, gfg7 commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamsMutation.cs
> +                throw new QueryException(result.Errors[0].Message);
Можешь подробнее описать, что хочешь видеть?
FluentResult хранит ошибки не как exception
FluentResult и graphql тоже разные IError
Если брать все ошибки и Select-ить в нужный тип, то подтянет еще и ошибку от самого graphql

```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "teamDelete"
      ],
      "extensions": {
        "message": "Команда с идентификатором '65184aae531f7242ef3963e6' не найдена",
        "stackTrace": null
      }
    }
  ]
}
```

2023-09-30 20:56 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamsMutation.cs
> +                throw new QueryException(result.Errors[0].Message);
Грубо - хочется, что-то типа такого:
```csharp
if (result.IsFailed)
{
    throw new AggregateException(result.Errors.Select(o => new Exception(o.Message)));
}
```

Но нужно проверить как такая связка себя ведет при реальной ошибке (и нескольких ошибках).

Если все хорошо - то можно запульнуть в extension-метод на `AggregateException`, чтобы можно было сделать типа: `AggregateException.FromErrors(result.Errors);`

2023-09-30 20:58 UTC, gfg7 commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamsMutation.cs
> +                throw new QueryException(result.Errors[0].Message);
Выше как раз результат как от твоего варианта

2023-09-30 21:01 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamsMutation.cs
> +                throw new QueryException(result.Errors[0].Message);
Можно еще вот так попробовать:
```csharp
if (result.IsFailed)
{
    throw new QueryException(result.Errors.Select(o => new Error(o.Message)));
}
```

2023-09-30 21:03 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamsMutation.cs
> +                throw new QueryException(result.Errors[0].Message);
А extension оформить можно вообще на Result:

```csharp
result.ThrowQueryExceptionIfHasErrors();
```

2023-10-01 07:31 UTC, picolino approved these changes

2023-10-01 07:32 UTC, merged