#21 Пользователь может удалить свой проект
habralab/garnet-team pull request #52
Opened 2023-10-02 20:56 UTC by Demorey

2023-10-02 21:37 UTC, picolino requested changes

2023-10-02 21:37 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectDelete/ProjectDelete.feature
> +        Тогда пользователь получает ошибку, что 'Проект может удалить только его владелец'
Подлей мастер, используем строготипизированные ошибки, см пример использования:
`TeamEditDescription.feature`

2023-10-02 21:37 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectDelete/ProjectDeleteSteps.cs
> +        _currentUserProviderFake.LoginAs(username);
В then-шагах под пользователем не логинимся
чтобы получить айдишник пользака по его имени можешь использовать метод `_currentUserProviderFake.GetUserIdByUsername`
(нужно подлить мастер)

2023-10-02 21:37 UTC, picolino commented on features/project/server/Garnet.Projects.AcceptanceTests/Features/ProjectDelete/ProjectDeleteSteps.cs
> +        var claims = _currentUserProviderFake.LoginAs(username);
А вот тут логин - правильно, так как действие совершает конкретный пользователь

2023-10-02 21:37 UTC, picolino commented on features/project/server/Garnet.Projects.Application/ProjectsService.cs
> +            return Result.Fail($"Проект с идентификатором '{projectId}' не найден");
Переходим на строготипизированные ошибки (комент выше)

2023-10-03 10:57 UTC, Demorey commented
Текст теста не менял, потому что если я поменяю только в одном сценарии, то надо менять везде иначе тест падает. В рамках ветки где буду менять все ошибки поправлю и текст в тестах.

2023-10-03 11:09 UTC, picolino requested changes

2023-10-03 11:09 UTC, picolino commented on features/project/server/Garnet.Projects.Application/Project.cs
> +    public static ProjectDeletedEvent EntityDeletedEvent(this Project doc)
Переименуй в ToDeletedEvent

2023-10-03 11:12 UTC, picolino approved these changes

2023-10-03 11:14 UTC, merged