#43 Пользователь может подавать заявки от имени своей команды на вступление в проект
habralab/garnet-team pull request #72
Opened 2023-10-07 17:32 UTC by gfg7

2023-10-07 22:57 UTC, picolino requested changes
Надо бы еще добавить мок-подписку на событие, которое будет приходить из вот этой истории: 
- #46

2023-10-07 22:57 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamJoinProjectRequest/TeamJoinProjectRequestPayload.cs
> +        string TeamId,
айдишник тоже нужно вернуть отсюда

2023-10-08 11:45 UTC, gfg7 commented
> Надо бы еще добавить мок-подписку на событие, которое будет приходить из вот этой истории:
> 
> * [📓 Пользователь может выносить вердикт по заявкам на вступление команды в свой проект #46](https://github.com/habralab/garnet-team/issues/46)

дождусь Дамира и сделаю ветку от него, чтобы не изобретать его же ивент

2023-10-08 20:19 UTC, picolino submitted a review, later dismissed

2023-10-08 20:40 UTC, picolino approved these changes

2023-10-08 20:40 UTC, merged