#87 Пользователь может редактировать теги своей команды
habralab/garnet-team pull request #98
Opened 2023-10-13 21:50 UTC by gfg7

2023-10-14 23:07 UTC, picolino requested changes

2023-10-14 23:07 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamEditName/TeamEditNamePayload.cs
> +    ) : TeamPayload(Id, Name, Description, AvatarUrl, Tags, OwnerUserId);
Я видел эти же изменения в соседнем ПР:
- #101

Надеюсь ты черри-пикала их, а не добавляла новыми коммитами, так как будут конфликты

2023-10-14 23:07 UTC, picolino commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamsMutation.cs
>          }
Убрать warning-и нужно

2023-10-15 12:26 UTC, gfg7 commented on features/team/server/Garnet.Teams.Infrastructure/Api/TeamEditName/TeamEditNamePayload.cs
> +    ) : TeamPayload(Id, Name, Description, AvatarUrl, Tags, OwnerUserId);
был неудачный мердж мастера
сначала мерджи в мастер эту ветку, на #79 порешаю

2023-10-15 12:43 UTC, picolino approved these changes

2023-10-15 12:43 UTC, merged